---
title: "Notepad"
output: html_document
---

```{r, message=FALSE}
#libraries:

library(tidyverse)
library(gridExtra)
library(grid)

# dataloading:

ade <- read.csv('source_data/ad_events.csv')
ads <- read.csv('derived_data/ads_cleaned.csv') %>% select(-X)
camp <- read.csv('source_data/campaigns.csv')
users <- read.csv('derived_data/user_cleaned.csv') %>% select(-X)
comp1 <- read.csv('derived_data/composite_data1.csv') %>% select(-X)
comp2 <- read.csv('derived_data/composite_data2.csv') %>% select(-X)
```



Questions that I want answered after data exploration:
2) Do campaigns/ ads actually draw in people of their target interest? On a similar note, do ads/ campaigns draw in the gender they want to draw in?
3) How does budget factor into the campaign? does higher budget = more people of that interest interacting with ads? Computation of a ratio of budget per day???
4) How does summer, winter/ seasons differ in terms of ad interactions? are there differences between the seasons? *Would probably want to take a look at those seasons as a separate variable??? *** be careful about the seasons, bc the dates do not match up... might be better to split as some sort of month or quarter intervals?
5) Relationship between platform, type of ad, and interactions and type of user
6) Relationship between type of user and time of day
7) Relationship between platform and location of user?
8) Prediction of gender via interests/ clustering